language: bash
sudo: true
dist: trusty
addons:
  apt:
#    update: true
#    sources:
#      - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
#        key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    packages:
      #- xvfb
      #- gnome-terminal
      #- wmctrl
      #- udev
      #- powershell
      - p7zip-full
      - realpath
      - bash
#branches:
#  only:
#    - master
#    - dev
env:
  global:
    #- DISPLAY=:99.0
    #- LANG=fr_FR.UTF-8
    - VSCode_Anywhere_CI=1
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
git:
  depth: 20
install:
  - unset GEM_PATH
  - unset GEM_HOME
  - unset MY_RUBY_HOME
  - unset rvm_bin_path
  - unset PYENV_ROOT
  - unset NVM_DIR
  - unset rvm_path
  - unset rvm_prefix
  - unset RAILS_ENV
  - unset GOROOT
  - unset GOPATH
#before_script:
  #- mkdir -p /tmp/{Linux,Windows}
  #- Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
  #- sleep 3
script:
  - cd /tmp && $TRAVIS_BUILD_DIR/Linux/install.sh --path /tmp --conf $TRAVIS_BUILD_DIR/Linux/VSCode-Anywhere.conf --user_conf $TRAVIS_BUILD_DIR/Linux/User_minimal.conf
  #- if [ "${TRAVIS_TAG}" != "" ]; then cd /tmp && 7za a -mx1 -mmt /tmp/VSCode-Anywhere-${TRAVIS_TAG}-Linux-amd64-minimal.bin -sfx VSCode-Anywhere >/dev/null; fi
  - if [ "${TRAVIS_TAG}" != "" ]; then cd /tmp && tar czf /tmp/VSCode-Anywhere-${TRAVIS_TAG}-Linux-amd64-minimal.tar.gz VSCode-Anywhere; fi
  - cp $TRAVIS_BUILD_DIR/Linux/User_recommended.conf /tmp/VSCode-Anywhere/Conf/User.conf
  - /tmp/VSCode-Anywhere/Tools/install.sh -c /tmp/VSCode-Anywhere/Conf/VSCode-Anywhere.conf -a /tmp/VSCode-Anywhere/Conf/User.conf
  #- if [ "${TRAVIS_TAG}" != "" ]; then cd /tmp && 7za a -mx1 -mmt /tmp/VSCode-Anywhere-${TRAVIS_TAG}-Linux-amd64-recommended.bin -sfx VSCode-Anywhere >/dev/null; fi
  - if [ "${TRAVIS_TAG}" != "" ]; then cd /tmp && tar czf /tmp/VSCode-Anywhere-${TRAVIS_TAG}-Linux-amd64-recommended.tar.gz VSCode-Anywhere; fi
  - cp $TRAVIS_BUILD_DIR/Linux/User_full.conf /tmp/VSCode-Anywhere/Conf/User.conf
  - /tmp/VSCode-Anywhere/Tools/install.sh -c /tmp/VSCode-Anywhere/Conf/VSCode-Anywhere.conf -a /tmp/VSCode-Anywhere/Conf/User.conf
  - /tmp/VSCode-Anywhere/Tools/install.sh -c /tmp/VSCode-Anywhere/Conf/VSCode-Anywhere.conf -a /tmp/VSCode-Anywhere/Conf/User.conf -u
  - /tmp/VSCode-Anywhere/Tools/install.sh -c /tmp/VSCode-Anywhere/Conf/VSCode-Anywhere.conf -a /tmp/VSCode-Anywhere/Conf/User.conf -f
  - /tmp/VSCode-Anywhere/Tools/install.sh -c /tmp/VSCode-Anywhere/Conf/VSCode-Anywhere.conf -a /tmp/VSCode-Anywhere/Conf/User.conf -l
  - yes | /tmp/VSCode-Anywhere/Tools/install.sh -c /tmp/VSCode-Anywhere/Conf/VSCode-Anywhere.conf -a /tmp/VSCode-Anywhere/Conf/User.conf -d
after_script:
  - test $(echo $(egrep -i 'error has occured' /tmp/VSCode-Anywhere/Logs/*) | wc -l) = 0
deploy:
#  - provider: releases
#    #body: my message
#    draft: true
#    prerelease: false
#    skip_cleanup: true
#    api_key:
#      secure: EzmyBGjtZl4tPmrO46dCm8S6aVsU+8rf7AbWjmGdv6umoOthaI9n46WDj7Obrr6IV70ujYewWj3F60VSO3XQb8f7tslgYprRjQQSwawrH6NsMzBCSAbPeyWaJe3EMu3ALa9vDnsWsY7JFtzvWWfDcJrTQo9QET5ZfmV5qcX9Z86cAqfuHckOQfOXtSeQIdVEsJPEz+QvUnmjDmIE+NVc3tB4KuiPRGXeFro5Eo5mFCRRmanYYm2R11tZqc4jmXNoWD4QU39LbsDskOLPKpmJqR5159kFe+cvYi6nB07zJTtbI92MVlvxiUuQ4ubwXOPZOik5YAHcUZ+50GPMf/blWSzyzfOXcRYDSNOx9HQQZp/qNfAuGe/teZwZmLtJYzWaDlNWDB++0tAJVpROPGpamvMWC0ksQQYQ3tnPOxSnm1/TH9PPmwwxLWV5ETDe0k95F39qNt8QEnJLpebw/V4DQ5QUI19n5a0QrailE6mxmTiMaYTAsbJk5N+MktfOmSc7tkrfl6HU6WMn4SphjiEw1rf4u4sNdBXG6CBq0mBpu+dNOe+Q8U1dawgOUW81yeNePbuik2QVAUk4pBKV7lFay6QnjfkkRy9hABlUhssJUzqFkf1NeB39cYMZavCXZHbRfN9ug4vuUayaFHiSou4D4ObvqeSNaoKcOlbaC4Ai+S4=
#    file_glob: true
#    file: VSCode-Anywhere-Linux-amd64-*.tar.gz
#    on:
#      branch: dev
  - provider: releases
    #body: my message
    draft: true
    prerelease: false
    skip_cleanup: true
    api_key:
      secure: EzmyBGjtZl4tPmrO46dCm8S6aVsU+8rf7AbWjmGdv6umoOthaI9n46WDj7Obrr6IV70ujYewWj3F60VSO3XQb8f7tslgYprRjQQSwawrH6NsMzBCSAbPeyWaJe3EMu3ALa9vDnsWsY7JFtzvWWfDcJrTQo9QET5ZfmV5qcX9Z86cAqfuHckOQfOXtSeQIdVEsJPEz+QvUnmjDmIE+NVc3tB4KuiPRGXeFro5Eo5mFCRRmanYYm2R11tZqc4jmXNoWD4QU39LbsDskOLPKpmJqR5159kFe+cvYi6nB07zJTtbI92MVlvxiUuQ4ubwXOPZOik5YAHcUZ+50GPMf/blWSzyzfOXcRYDSNOx9HQQZp/qNfAuGe/teZwZmLtJYzWaDlNWDB++0tAJVpROPGpamvMWC0ksQQYQ3tnPOxSnm1/TH9PPmwwxLWV5ETDe0k95F39qNt8QEnJLpebw/V4DQ5QUI19n5a0QrailE6mxmTiMaYTAsbJk5N+MktfOmSc7tkrfl6HU6WMn4SphjiEw1rf4u4sNdBXG6CBq0mBpu+dNOe+Q8U1dawgOUW81yeNePbuik2QVAUk4pBKV7lFay6QnjfkkRy9hABlUhssJUzqFkf1NeB39cYMZavCXZHbRfN9ug4vuUayaFHiSou4D4ObvqeSNaoKcOlbaC4Ai+S4=
    file_glob: true
    file: VSCode-Anywhere-*.tar.gz
    on:
      tags: true