
platform: x64

#branches:
#  only:
#    - master
#    - dev

only_commits:
  files:
    - Windows/*.conf
    - Windows/*.ps1
    - appveyor.yml

environment:
  VSCode_Anywhere_CI: true

clone_depth: 20

install:
  - ps: Windows\install.ps1 -conf Windows\VSCode-Anywhere.conf -user_conf Windows\User_minimal.conf -path C:\
  - ps: if ("${Env:APPVEYOR_REPO_TAG_NAME}") { C:\VSCode-Anywhere\Third-Party\7-zip\install\7za.exe a -mmt C:\projects\vscode-anywhere\VSCode-Anywhere-${Env:APPVEYOR_REPO_TAG_NAME}-Win64-minimal.zip C:\VSCode-Anywhere }
  - ps: Copy-Item "C:\projects\vscode-anywhere\Windows\User_recommended.conf" -Destination "C:\VSCode-Anywhere\Conf\User.conf"
  - ps: C:\VSCode-Anywhere\Tools\install.ps1 -conf C:\VSCode-Anywhere\Conf\VSCode-Anywhere.conf -user_conf C:\VSCode-Anywhere\Conf\User.conf
  - ps: if ("${Env:APPVEYOR_REPO_TAG_NAME}") { C:\VSCode-Anywhere\Third-Party\7-zip\install\7za.exe a -mmt C:\projects\vscode-anywhere\VSCode-Anywhere-${Env:APPVEYOR_REPO_TAG_NAME}-Win64-recommended.zip C:\VSCode-Anywhere }
  - ps: Copy-Item "C:\projects\vscode-anywhere\Windows\User_full.conf" -Destination "C:\VSCode-Anywhere\Conf\User.conf"
  - ps: C:\VSCode-Anywhere\Tools\install.ps1 -conf C:\VSCode-Anywhere\Conf\VSCode-Anywhere.conf -user_conf C:\VSCode-Anywhere\Conf\User.conf
  - ps: C:\VSCode-Anywhere\Tools\install.ps1 -conf C:\VSCode-Anywhere\Conf\VSCode-Anywhere.conf -user_conf C:\VSCode-Anywhere\Conf\User.conf -update
  - ps: C:\VSCode-Anywhere\Tools\install.ps1 -conf C:\VSCode-Anywhere\Conf\VSCode-Anywhere.conf -user_conf C:\VSCode-Anywhere\Conf\User.conf -link
  - ps: if (Get-Content C:\VSCode-Anywhere\Logs\* | Select-String -Pattern 'error has occurred') { exit 1 }
  - ps: Set-Location "C:\projects\vscode-anywhere"

artifacts:
  - path: VSCode-*.zip
    name: VSCode-Anywhere-Win64

#https://www.appveyor.com/docs/deployment/github/
deploy:
#  - provider: GitHub
#    name: branch
#    #release: $(APPVEYOR_REPO_TAG_NAME)
#    description: |
#      1st packaged version of VSCode-Anywhere.
#    auth_token:
#      secure: ld6PNFxh5Mp4/xa7/Kud00ABN8flWZUjGzeIhlmEqVETRi4kC7ZRdpaTOUcAE4Fi # your encrypted token from GitHub
#    artifact: VSCode-Anywhere-Win64
#    draft: false
#    prerelease: false
#    force_update: true
#    on:
#      branch: dev

  - provider: GitHub
    name: tag
    #release: $(APPVEYOR_REPO_TAG_NAME)
    description: |
      1st packaged version of VSCode-Anywhere.
    auth_token:
      secure: ld6PNFxh5Mp4/xa7/Kud00ABN8flWZUjGzeIhlmEqVETRi4kC7ZRdpaTOUcAE4Fi # your encrypted token from GitHub
    artifact: VSCode-Anywhere-Win64
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true        # deploy on tag push only

#skip_commits:
#  files:
#    - '*.md'
#    - Linux/*
#    - Screenshots/*

build: off