include:
    - salt/core/env
    - salt/core/nix
    - salt/core/brew
    - salt/core/scoop
    - salt/core/chocolatey
    - salt/core/msys2
    - salt/core/vscode
    - salt/core/zeal
    - salt/core/saltstack
    - salt/core/git
    - salt/core/terminal
    - salt/core/misc