default:
  enabled: False
  # pip:
  #   opts:
  #     global: {}
  #     install:
  #       upgrade: False
  #     update:
  #       upgrade: True
  #     uninstall: {}
  #   pkgs: {}
  vscode:
    extensions:
      vscoss.vscode-ansible:
        enabled: True
        version: null
  zeal:
    docsets:
      Ansible:
        enabled: True
      Jinja:
        enabled: True
# Windows:
#   vscode:
#     extensions:
#       haaaad.ansible:
#         enabled: True
#         version: null
Linux:
  brew:
    pkgs:
      ansible:
        enabled: True
  # pip:
  #   opts:
  #     global:
  #       bin_env: /home/linuxbrew/.linuxbrew/bin/pip3
  #   pkgs:
  #     ansible: # not compatible with Windows
  #       enabled: True
  #       version: null
  #       opts:
  #         install: {}
  #         update: {}
  #         uninstall: {}