# Generated by carnix 0.10.0: carnix generate-nix --src ./. --standalone
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# vscode-anywhere-chroot-0.1.0

    crates.vscode_anywhere_chroot."0.1.0" = deps: { features?(features_.vscode_anywhere_chroot."0.1.0" deps {}) }: buildRustCrate {
      crateName = "vscode-anywhere-chroot";
      version = "0.1.0";
      authors = [ "Ghislain LE MEUR" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."nix"."${deps."vscode_anywhere_chroot"."0.1.0"."nix"}" deps)
        (cratesIO.crates."tempdir"."${deps."vscode_anywhere_chroot"."0.1.0"."tempdir"}" deps)
      ]);
    };
    features_.vscode_anywhere_chroot."0.1.0" = deps: f: updateFeatures f (rec {
      nix."${deps.vscode_anywhere_chroot."0.1.0".nix}".default = true;
      tempdir."${deps.vscode_anywhere_chroot."0.1.0".tempdir}".default = true;
      vscode_anywhere_chroot."0.1.0".default = (f.vscode_anywhere_chroot."0.1.0".default or true);
    }) [
      (cratesIO.features_.nix."${deps."vscode_anywhere_chroot"."0.1.0"."nix"}" deps)
      (cratesIO.features_.tempdir."${deps."vscode_anywhere_chroot"."0.1.0"."tempdir"}" deps)
    ];


# end

  };

  vscode_anywhere_chroot = crates.crates.vscode_anywhere_chroot."0.1.0" deps;
  __all = [ (vscode_anywhere_chroot {}) ];
  deps.bitflags."1.0.4" = {};
  deps.cc."1.0.29" = {};
  deps.cfg_if."0.1.6" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.libc."0.2.48" = {};
  deps.nix."0.13.0" = {
    bitflags = "1.0.4";
    cfg_if = "0.1.6";
    libc = "0.2.48";
    void = "1.0.2";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.48";
    winapi = "0.3.6";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.remove_dir_all."0.5.1" = {
    winapi = "0.3.6";
  };
  deps.tempdir."0.3.7" = {
    rand = "0.4.6";
    remove_dir_all = "0.5.1";
  };
  deps.void."1.0.2" = {};
  deps.vscode_anywhere_chroot."0.1.0" = {
    nix = "0.13.0";
    tempdir = "0.3.7";
  };
  deps.winapi."0.3.6" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
}
