default:
  enabled: False
  vscode:
    extensions:
      ms-azuretools.vscode-docker:
        enabled: True
        version: null
    settings:
      dash.languageIdToDocsetMap.dockerfile:
        - docker
  zeal:
    docsets:
      Docker:
        enabled: True
Linux:
  nix:
    pkgs:
      docker:
        enabled: True
        attr: nixpkgs.docker
      docker-compose:
        enabled: True
        attr: nixpkgs.docker-compose
Macos:
  brew:
    pkgs:
      homebrew/cask/docker:
        enabled: True
      hombrew/cask/virtualbox:
        enabled: True
      docker-compose:
        enabled: True